/* eslint-disable */
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR ='GET_CATEGORIES_ERROR'

export const GET_CATEGORIES_ID = 'GET_CATEGORIES_ID'
export const GET_CATEGORIES_SUCCESS_ID = 'GET_CATEGORIES_SUCCESS_ID'
export const GET_CATEGORIES_ERROR_ID ='GET_CATEGORIES_ERROR_ID'

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'
export const UPDATE_CATEGORIES_SUCCESS = 'UPDATE_CATEGORIES_SUCCESS'
export const UPDATE_CATEGORIES_ERROR = 'UPDATE_CATEGORIES_ERROR'

export const DELETE_CATEGORIES = 'DELETE_CATEGORIES'
export const DELETE_CATEGORIES_SUCESS = 'DELETE_CATEGORIES_SUCESS'
export const DELETE_CATEGORIES_ERROR = 'DELETE_CATEGORIES_ERROR'

export const POST_CATEGORIES = 'POST_CATEGORIES'
export const POST_CATEGORIES_SUCCESS = 'POST_CATEGORIES_SUCCESS'
export const POST_CATEGORIES_ERROR = 'POST_CATEGORIES_ERROR'
